[package]
name = "notrum-core"
version = "0.1.0"
edition = "2024"
publish = false
license.workspace = true
authors.workspace = true

[features]
test-utils = [
    "notrum-recovery/test-utils",
    "notrum-secure/test-utils",
    "notrum-security/test-utils",
    "notrum-storage/test-utils",
]

[lib]
path = "src/lib.rs"

[dependencies]
notrum-editor = { version = "0.1.0", path = "../notrum-editor" }
notrum-engine = { version = "0.1.0", path = "../notrum-engine" }
notrum-frontmatter = { version = "0.1.0", path = "../notrum-frontmatter" }
notrum-markdown = { version = "0.1.0", path = "../notrum-markdown" }
notrum-recovery = { version = "0.1.0", path = "../notrum-recovery" }
notrum-rss = { version = "0.1.0", path = "../notrum-rss" }
notrum-secure = { version = "0.1.0", path = "../notrum-secure" }
notrum-security = { version = "0.1.0", path = "../notrum-security" }
notrum-storage = { version = "0.1.0", path = "../notrum-storage" }

[dev-dependencies]
notrum-recovery = { version = "0.1.0", path = "../notrum-recovery", features = ["test-utils"] }
notrum-secure = { version = "0.1.0", path = "../notrum-secure", features = ["test-utils"] }
notrum-security = { version = "0.1.0", path = "../notrum-security", features = ["test-utils"] }
notrum-storage = { version = "0.1.0", path = "../notrum-storage", features = ["test-utils"] }
